name: cathay_591
channels:
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - automat=20.2.0
  - bcrypt=3.2.0
  - brotlipy=0.7.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cffi=1.14.6
  - colorama=0.4.4
  - constantly=15.1.0
  - cryptography=3.4.7
  - cssselect=1.1.0
  - hyperlink=21.0.0
  - idna=3.2
  - importlib_metadata=3.10.0
  - incremental=17.5.0
  - iniconfig=1.1.1
  - itemadapter=0.3.0
  - libiconv=1.15
  - libxml2=2.9.12
  - libxslt=1.1.34
  - lxml=4.6.3
  - more-itertools=8.8.0
  - openssl=1.1.1k
  - packaging=21.0
  - parsel=1.5.2
  - pip=21.1.3
  - pluggy=0.13.1
  - protego=0.1.16
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydispatcher=2.0.5
  - pyhamcrest=2.0.2
  - pymongo=3.12.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.2.4
  - pytest-runner=5.3.1
  - python=3.7.10
  - pywin32=227
  - queuelib=1.5.0
  - scrapy=2.4.1
  - selenium=3.141.0
  - service_identity=18.1.0
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - toml=0.10.2
  - twisted=21.2.0
  - twisted-iocpsupport=1.0.1
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - w3lib=1.21.0
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - zipp=3.5.0
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=5.4.0
  - pip:
    - click==8.0.1
    - flasgger==0.9.5
    - flask==2.0.1
    - importlib-metadata==4.6.1
    - itsdangerous==2.0.1
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - markupsafe==2.0.1
    - mistune==0.8.4
    - pyrsistent==0.18.0
    - pyyaml==5.4.1
    - werkzeug==2.0.1
